#!/usr/bin/env bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2016, Joyent, Inc.
#

#
# Run API tests.
#
# This creates .tap files in OUTPUT_DIR that can be processed by a TAP reader.
# Testing config and log files are also placed in this dir.
#
# Run `./runtests -h` for usage info.
#

API=fwapi
if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail



#---- guard

guard_file=/lib/sdc/.sdc-test-no-production-data
if [[ ! -f "$guard_file" ]]; then
    cat <<EOF
To run this test you must create the file:

    $guard_file

after ensuring you have no production data on this SDC.
EOF
    exit 2
fi



#---- support functions

function fatal
{
    echo "$(basename $0): fatal error: $*"
    exit 1
}

function usage
{
    echo "Usage:"
    echo "  runtests [OPTIONS...]"
    echo ""
    echo "Options:"
    echo "  -f FILTER   Filter pattern (substring match) for test files to run."
    echo "  -s          Stop on first error."
}



#---- mainline

start_time=$(date +%s)

TOP=$(cd $(dirname $0)/../; pwd)
NODE_INSTALL=$TOP/node


# Options.
opt_test_pattern=
opt_stop_on_failure=
while getopts "hf:s" opt
do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        f)
            opt_test_pattern=$OPTARG
            ;;
        s)
            opt_stop_on_failure="true"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done


# Setup a clean output dir.
OUTPUT_DIR=/var/tmp/${API}test
echo "# Setup a clean output dir ($OUTPUT_DIR)."
rm -rf $OUTPUT_DIR
mkdir -p /$OUTPUT_DIR

cd $TOP

# Run the integration tests
multi_test_files=
test_files=$(ls -1 test/integration/*.test.js)
if [[ -n "$opt_test_pattern" ]]; then
    test_files=$(echo "$test_files" | grep "$opt_test_pattern" || true)
    echo "# Running filtered set of test files: $test_files"
fi

vmapi_url=$(json -f /opt/smartdc/fwapi/config.json vmapi.url)
cnapi_url=${vmapi_url//vmapi/cnapi}

num_servers=$(curl -sS ${cnapi_url}/servers | json -a uuid setup | grep true | wc -l)
if [[ ${num_servers} -gt 1 ]]; then
    echo "# More than 1 server: running multi-server tests"
    multi_test_files=$(ls -1 test/integration/*.multi-test.js)

    if [[ ! -f /opt/smartdc/fwapi/test/config.json ]]; then
        # No test config present - generate it
        /opt/smartdc/fwapi/test/bin/gen-multi-test-config
    fi

    [[ ! -f /opt/smartdc/fwapi/test/config.json ]] && fatal "Could not generate multi-server test config"
fi

echo ""
set +o errexit

test_failed=

for file in $test_files $multi_test_files; do
    test_file=$(basename $file)
    echo "# $test_file"

    PATH=$NODE_INSTALL/bin:$PATH node $file \
        | tee $OUTPUT_DIR/$test_file.tap

    # If a test program crashes, ensure that this
    # script exits non-zero.
    if [[ "$?" != "0" ]]; then
       if [[ -n "$opt_stop_on_failure" ]]; then
           break
       else
           test_failed="true"
       fi
   fi
done

set -o errexit

echo ""
echo "# test output in $OUTPUT_DIR:"
cd $OUTPUT_DIR
ls *.tap


# Colored summary of results (borrowed from smartos-live.git/src/vm/run-tests).
echo ""
echo "# test results:"

end_time=$(date +%s)
elapsed=$((${end_time} - ${start_time}))

tests=$(grep "^# tests [0-9]" $OUTPUT_DIR/*.tap | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
passed=$(grep "^# pass  [0-9]" $OUTPUT_DIR/*.tap | tr -s ' ' | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
[[ -z ${tests} ]] && tests=0
[[ -z ${passed} ]] && passed=0
fail=$((${tests} - ${passed}))

echo "# Completed in ${elapsed} seconds."
echo -e "# \033[32mPASS: ${passed} / ${tests}\033[39m"
if [[ ${fail} -gt 0 ]]; then
    echo -e "# \033[31mFAIL: ${fail} / ${tests}\033[39m"
    echo ""
    echo -e "# \033[31mFAILING TESTS:\033[39m"
    grep -l "^# fail  [0-9]" ${OUTPUT_DIR}/*.tap | sed -e "s,${OUTPUT_DIR}/,," -e 's,.tap,,' -e 's,^,#   ,'
fi
echo ""

if [[ -n ${test_failed} || ${tests} != ${passed} ]]; then
    exit 1
fi
