#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2015, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE="root@$1"

while [[ -z "$FWAPI_ZONE" ]]; do
    echo "Trying to get FWAPI zone"
    FWAPI_ZONE=$(ssh $NODE "/opt/smartdc/bin/sdc-vmapi /vms?alias=fwapi0" 2>/dev/null \
        | json -H -c 'this.tags && this.tags.smartdc_role === "fwapi"' \
            -c 'this.state === "running"' 0.uuid)
done
echo "FWAPI_ZONE: $FWAPI_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$FWAPI_ZONE/root/opt/smartdc/fwapi/node_modules
fi

rsync -avz ${TOP}/ \
    $NODE:/zones/$FWAPI_ZONE/root/opt/smartdc/fwapi/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /deps/ \
    --exclude /tools/ \
    --exclude /tmp/

state=$(ssh ${NODE} svcs -z ${FWAPI_ZONE} -H -o state fwapi)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${FWAPI_ZONE} clear fwapi
else
    ssh ${NODE} svcadm -z ${FWAPI_ZONE} restart fwapi
fi
